services:
  splitwise_db:
    image: mysql:8.4
    container_name: splitwise_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: splitwise_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  splitwise_pma:
    image: phpmyadmin/phpmyadmin
    container_name: splitwise_pma
    restart: unless-stopped
    environment:
      PMA_HOST: splitwise_db
      PMA_PORT: 3306
    ports:
      - 8081:80
volumes:
  dbdata:
